### PR TITLE
CI: Deploy to the VSCode marketplace

### LINKED ISSUE #21: Set-up CI for automated releases into the VSCode extension marketplace
Currently, there's [`deploy.yml`](https://github.com/effekt-lang/effekt-vscode/blob/master/.github/workflows/deploy.yml), but it doesn't actually deploy the resulting extension _to the VSCode extension marketplace_. This causes version divergence: currently there's v0.1.5 on GitHub, but v0.1.10 on the VSCode extension marketplace [?!].
Here's what the official docs say: https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions; we can already create the `vsix` file, it's just a matter of uploading it correctly.

As a follow-up, we could also deploy into other registries like https://open-vsx.org; I think @marvinborner was interested in that.

### PR DESCRIPTION
**Pull request by jiribenes**
Resolves #21

**Untested**, needs `VSCE_PAT` (a personal access token for publishing an extension, see [here](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token))

### CODE REVIEW

**Comment by jiribenes** [comment]
Could you generate a PAT for VSCode Marketplace (see link above) and add it to the [repo secrets](https://github.com/effekt-lang/effekt-vscode/settings/secrets/actions), @b-studios?
Then we could merge this and test it -- it's not a one-click release, but it's close enough for what we need.

**Comment by jiribenes** [comment]
Thanks for the token, let's try this! :)

**Comment by jiribenes** [comment]
Everything seems to have worked the first time 🥳
Since I can't put it into the README, here's how to release a new version:

---

Run the following commands to release a new version:
```sh
# Make sure you're on the latest `master`

git checkout master && git pull

# Depending on if the new change is minor or a patch
# Creates a commit with the version bump and a tag

npm version minor/patch

# Push the resulting commit (feel free to amend it before if you want to change its name)

git push 

# Push the tag

git push --tags
```
then go see if the release went okay in the Actions tab: https://github.com/effekt-lang/effekt-vscode/actions/workflows/deploy.yml.

**Comment by b-studios** [comment]
> Since I can't put it into the README

Can't we put this into something like `CONTRIBUTE.md` or the like?

**Pull request merged**
